name: "chat gpt me"
description: "create a readme description"

inputs:
  CHAT_GPT_API_KEY:
    required: true
  MARKDOWN_FILE:
      required: false
  WAKATIME_API_KEY:
      required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.message }}