name: "chat gpt me"
description: "create a readme description with chatgpt and wakatime metrics"

inputs:
  CHAT_GPT_API_KEY:
    required: false
  WAKATIME_API_KEY:
    required: false

runs:
  using: docker
  image: Dockerfile
  args: 
  - ${{ inputs.CHAT_GPT_API_KEY }}
  - ${{ inputs.WAKATIME_API_KEY }}