name: Testing deploy with custom github action

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test action chatgpt me
      uses: brutalzinn/action-chatgpt-me@v10
