name: Testing deploy with custom github action

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test action chatgpt me
      uses: brutalzinn/action-chatgpt-me@main
      env:
          CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
              
    - name: Commit and push update
      run: |-
        git config --global user.email "test@action.com"
        git config --global user.name "Chat GPT me"
        git add -A
        git commit -m "Added presentation from GitHub Actions"
        git push
