name: Testing deploy with custom github action

on:
  push:
    branches: [ "main" ]

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test action chatgpt me
      uses: brutalzinn/action-chatgpt-me@v1
      with:
        CHAT_GPT_API_KEY: 'test'
        MARKDOWN_FILE: 'README.md'
        WAKATIME_API_KEY: 'test'