jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: brutalzinn/action-chatgpt-me@v1
      	with:
        	message: hello world action message.